# Configuration file for language group generation

# Common language groups used across all tasks
language_groups:
  swiss:
    - de  # German
    - fr  # French
    - it  # Italian

  europe:
    - ca  # Catalan
    - cs  # Czech
    - da  # Danish
    - de  # German
    - el  # Greek
    - en  # English
    - es  # Spanish
    - eu  # Basque
    - fr  # French
    - hr  # Croatian
    - hu  # Hungarian
    - it  # Italian
    - lt  # Lithuanian
    - nl  # Dutch
    - pl  # Polish
    - pt  # Portuguese
    - ro  # Romanian
    - ru  # Russian
    - sk  # Slovak
    - sr  # Serbian
    - sv  # Swedish
    - tr  # Turkish
    - uk  # Ukrainian

  global:
    # European languages
    - ca
    - cs
    - da
    - de
    - el
    - en
    - es
    - eu
    - fr
    - hr
    - hu
    - it
    - lt
    - nl
    - pl
    - pt
    - ro
    - ru
    - sk
    - sr
    - sv
    - tr
    - uk
    # Asian languages
    - ar  # Arabic
    - bn  # Bengali
    - fa  # Persian/Farsi
    - fil # Filipino
    - gu  # Gujarati
    - he  # Hebrew
    - hi  # Hindi
    - hy  # Armenian
    - id  # Indonesian
    - ja  # Japanese
    - kn  # Kannada
    - ko  # Korean
    - ky  # Kyrgyz
    - ml  # Malayalam
    - mr  # Marathi
    - ms  # Malay
    - ne  # Nepali
    - si  # Sinhala
    - ta  # Tamil
    - te  # Telugu
    - vi  # Vietnamese
    - zh  # Chinese
    # African languages
    - am  # Amharic
    - ha  # Hausa
    - ig  # Igbo
    - mg  # Malagasy
    - ny  # Chichewa/Nyanja
    - sn  # Shona
    - so  # Somali
    - sw  # Swahili
    - yo  # Yoruba

# Language code to full language name mapping
language_mapping:
  ar: "Arabic"
  az: "Azerbaijani"
  be: "Belarusian"
  bg: "Bulgarian"
  bn: "Bengali"
  de: "German"
  el: "Greek"
  es: "Spanish"
  et: "Estonian"
  eu: "Basque"
  fa: "Persian"
  fi: "Finnish"
  fr: "French"
  he: "Hebrew"
  hi: "Hindi"
  hr: "Croatian"
  hu: "Hungarian"
  hy: "Armenian"
  id: "Indonesian"
  it: "Italian"
  ja: "Japanese"
  ka: "Georgian"
  kk: "Kazakh"
  ko: "Korean"
  lt: "Lithuanian"
  mk: "North Macedonian"
  ml: "Malayalam"
  ms: "Malay"
  ne: "Nepali"
  nl: "Dutch"
  pl: "Polish"
  pt: "Portuguese"
  ru: "Russian"
  sr: "Serbian"
  ta: "Tamil"
  te: "Telugu"
  tl: "Tagalog"
  tr: "Turkish"
  uk: "Ukrainian"
  ur: "Urdu"
  uz: "Uzbek"
  vi: "Vietnamese"
  zh: "Chinese"

# Task configurations
tasks:
  global_mmlu:
    base_dir: "lm_eval/tasks/global_mmlu/full"
    output_dir: "lm_eval/tasks/global_mmlu/full"
    task_pattern: "global_mmlu_full_{lang}"
    subject_pattern: "global_mmlu_full_{lang}_{subject}"
    group_pattern: "global_mmlu_full_{group}"
    has_subjects: true
    subjects:
      - stem
      - humanities
      - social_sciences
      - other

  hellaswag:
    base_dir: "lm_eval/tasks/okapi/hellaswag_multilingual"
    output_dir: "lm_eval/tasks/okapi/hellaswag_multilingual"
    task_pattern: "hellaswag_{lang}"
    group_pattern: "hellaswag_{group}"
    has_subjects: false
    subjects: []

  arc:
    base_dir: "lm_eval/tasks/okapi/arc_multilingual"
    output_dir: "lm_eval/tasks/okapi/arc_multilingual"
    task_pattern: "arc_{lang}"
    group_pattern: "arc_{group}"
    has_subjects: false
    subjects: []

  xwinograd:
    base_dir: "lm_eval/tasks/xwinograd"
    output_dir: "lm_eval/tasks/xwinograd"
    task_pattern: "xwinograd_{lang}"
    group_pattern: "xwinograd_{group}"
    has_subjects: false
    subjects: []

  xnli:
    base_dir: "lm_eval/tasks/xnli"
    output_dir: "lm_eval/tasks/xnli"
    task_pattern: "xnli_{lang}"
    group_pattern: "xnli_{group}"
    has_subjects: false
    subjects: []

  xcopa:
    base_dir: "lm_eval/tasks/xcopa"
    output_dir: "lm_eval/tasks/xcopa"
    file_pattern: "default_{lang}.yaml"  # File names on disk
    task_pattern: "xcopa_{lang}"         # Task names referenced in YAML
    group_pattern: "xcopa_{group}"
    has_subjects: false
    subjects: []

  include:
    base_dir: "lm_eval/tasks/include/default"
    output_dir: "lm_eval/tasks/include/default"
    task_pattern: "include_base_44_{lang_name}"
    subject_pattern: "include_base_44_{lang_name}_{subject}"
    group_pattern: "include_base_44_{group}"
    has_subjects: true
    subjects:
      - applied_science
      - arts_humanities
      - business_commerce
      - driving_license
      - general_knowledge
      - health_oriented_education
      - marine_license
      - medical_license
      - professional_certification
      - social_science
      - stem
    use_full_language_names: true 